### ISSUE TITLE
function の書き方について

### ISSUE THREAD

**Issue by baron-tommy** [rhysd/node-github-emoji#1]
バグなどではありません
もし良ければ回答あると 嬉しいなと思います

arrow function をあまり利用しないのは、 TypeScripの場合*型*があり
可読性が落ちるからでしょうか...?

```ts
const myFunc = (p: string): string => 'myFuncです'
```

**Comment by rhysd** [comment]
むしろトップレベルで積極的に arrow function を使う理由って何かありますか？

**Comment by baron-tommy** [comment]
同じ処理をするなら文字数が、少ない方がいいのかなと思っています
故に、この質問を書きました。

**Comment by rhysd** [comment]
```
function foo() {}
const foo = () => {}
```

いやむしろ長く見えますが

**Comment by baron-tommy** [comment]
おっしゃるとおりだと思います
回答ありがとうございました
